version: '3'

services:
  mysql:
    image: percona/percona-server:8.0.26
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=ft_extra
      - MYSQL_USER=ft_extra
      - MYSQL_PASSWORD=123456
    command: ["--character-set-server=utf8", "--collation-server=utf8_general_ci"]
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql

  php:
    build: ./php
    volumes:
      - ./converter:/var/www/html

  nginx:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - php
    volumes:
      - ./converter:/var/www/html
    environment:
      - FASTCGI_HOST=php
